### ISSUE TITLE
SCSS compilation : rgba becomes hsla + throwing error 

### ISSUE THREAD

**Issue by xavianaxw** [vigetlabs/blendid#509]
I have a scenario when compiling my css where I have a property in my `scss` file that looks something like this:

```scss
$concrete: #f2f2f2;

.el {
   background-color: rgba($concrete, 0.75);
}
```

Upon compiling it will look something like this:

```scss
.el {
   background-color: hsla(0,0%,95%,.75);
}
```

which throws an invalid on Google Chrome.
